resources:
  - ../../base
namespace: develop
commonLabels:
  tier: backend
images:
  - name: service-image
    newName: ${ECR_REPO} # {"$imagepolicy": "${ENVIRONMENT}:img-upd-${SERVICE_NAME}:name"}
    newTag: develop # {"$imagepolicy": "${ENVIRONMENT}:${SERVICE_NAME}:tag"}

patches:
  - path: patch-service-account.yaml
  - path: patch-deployment.yaml
