apiVersion: batch/v1
kind: Job
metadata:
  name: job-${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
    tier: ${TIER}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
        tier: ${TIER}
    spec:
      serviceAccountName: sa-${SERVICE_NAME}-service
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 10003
        runAsGroup: 30001
      containers:
      - name: ${SERVICE_NAME}-container
        image: service-image
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        env:
        - name: AWS_REGION
        value: ${AWS_REGION}
        resources:
          requests:
            memory: "50Mi"   ###### VALIDATE THESE WERE RANDOM NUMBERS TO TEST
          limits:
            memory: "100Mi"  ###### VALIDATE THESE WERE RANDOM NUMBERS TO TEST