redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  extraEnv:
    - name: ARGOCD_SERVER_INSECURE
      value: "true"

repoServer:
  replicas: 1

applicationSet:
  replicas: 1