apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${SERVICE_NAME}
spec:
  template:
    metadata:
      labels:
        istio.io/dataplane-mode: ambient
    spec:
      containers:
      - name: ${SERVICE_NAME}-container
        env:
        - name: DYNAMODB_PAYMENT_TABLE
          value: ${DYNAMODB_TABLE_NAME}
        - name: AWS_REGION
          value: ${AWS_REGION}
        - name: OTEL_COLLECTOR
          value: otel-collector-opentelemetry-collector.observability.svc.cluster.local
        - name: SERVICE_NAME
          value: ${SERVICE_NAME}
          