apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: ${ENVIRONMENT}
  annotations:
    cert-manager.io/cluster-issuer: danielrive-letsencrypt2
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ${ENVIRONMENT}.smartcash.danielrive.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  tls: 
  - hosts:
    - ${ENVIRONMENT}.smartcash.danielrive.site
    secretName: frontend-tls

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: danielrive-letsencrypt2
spec:
  ingressClassName: nginx
  rules:
  - host: monitoring.${ENVIRONMENT}.smartcash.danielrive.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80
  tls: 
  - hosts:
    - monitoring.${ENVIRONMENT}.smartcash.danielrive.site
    secretName: grafana-tls