apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gw-ingress
  namespace: ${ENVIRONMENT}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: api.${ENVIRONMENT}.smartcash.danielrive.site
    http:
      paths:
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: user
            port:
              number: 80
      - path: /expenses
        pathType: Prefix
        backend:
          service:
            name: expenses
            port:
              number: 80
      - path: /bank
        pathType: Prefix
        backend:
          service:
            name: bank
            port:
              number: 80
      - path: /payment
        pathType: Prefix
        backend:
          service:
            name: payment
            port:
              number: 80