apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-traces
  namespace: observability
spec:
  strategy: production
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx # Ingress annotations here
    ingressClassName: nginx
    hosts:
      - jaeger.smartcash.rootkit.site #your domain name.
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
