#########################################################
######## Trust in AWS ECR registry only for workloads 

apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: trustregistry
spec:
  crd:
    spec:
      names:
        kind: TrustRegistry
      validation:
        openAPIV3Schema:
          type: object
          properties:
            registry:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package trustregistry 

        import future.keywords

        violation[{"msg": msg, "details": {"images MUST come from trusted registry"}}] {
              some container in input.review.object.spec.containers
              not startswith(container.image, input.parameters.registry)
              msg := sprintf("Image '%v' comes from untrusted registry", [container.image])
  
        }

---

#########################################
######## Container security 

apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: containersecurity
spec:
  crd:
    spec:
      names:
        kind: ContainerSecurity
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package containersecurity 

        import future.keywords

        violation[{"msg": msg, "details": {"images MUST come from trusted registry"}}] {
              some container in input.review.object.spec.containers
              container.securityContext.allowPrivilegeEscalation != "false"
              msg := sprintf("Container '%v' allow privilege escalation", [container.name])
        }