#!/bin/bash
##Generated by AmazonQ 
# Script to generate commit messages using git diff information

# Get the staged changes
DIFF_OUTPUT=$(git diff --cached --stat)
DIFF_DETAILS=$(git diff --cached)

# Create a temporary file with the changes
TMP_FILE=$(mktemp)
echo "# Generate a concise and descriptive commit message for these changes:" > $TMP_FILE
echo "" >> $TMP_FILE
echo "## Files changed:" >> $TMP_FILE
echo "\`\`\`" >> $TMP_FILE
echo "$DIFF_OUTPUT" >> $TMP_FILE
echo "\`\`\`" >> $TMP_FILE
echo "" >> $TMP_FILE
echo "## Changes details:" >> $TMP_FILE
echo "\`\`\`" >> $TMP_FILE
echo "$DIFF_DETAILS" >> $TMP_FILE
echo "\`\`\`" >> $TMP_FILE

# Display instructions
echo "Changes have been captured. You can now:"
echo "1. Open your IDE's Amazon Q chat"
echo "2. Copy and paste the contents of this file: $TMP_FILE"
echo "3. Ask Amazon Q to 'Generate a commit message for these changes'"
echo ""
echo "Temporary file with changes created at: $TMP_FILE"
echo "You can view it with: cat $TMP_FILE"