apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ${SERVICE_NAME}
spec:
  image: ${ECR_REPO}
  interval: 1m0s
  timeout: 10m0s
  provider: aws

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ${SERVICE_NAME}
spec:
  imageRepositoryRef:
    name: ${SERVICE_NAME}
  filterTags:
    pattern: '^${ENVIRONMENT}-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: img-upd-${SERVICE_NAME}
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@smartcash.com
        name: fluxcdbot
    push:
      branch: ${ENVIRONMENT}
  update:
    path: ${PATH_DEPLOYMENT}