apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-nginx-to-bank
spec:
  podSelector:
    matchLabels:
      app: bank
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          ingress: nginx
    ports:
    - protocol: TCP
      port: 80