apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${SERVICE_NAME}-service
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "services/${SERVICE_NAME}-service/overlays/${ENVIRONMENT}"
  prune: true
  postBuild:
    substitute:
      APP_Version: "test"