apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
      - name: ${SERVICE_NAME}-container
        image: ${ECR_REPO} # {"$imagepolicy": "${ENVIRONMENT}:img-upd-${SERVICE_NAME}"}
        env:
        - name: DYNAMODB_EXPENSES_TABLE
          value: ${DYNAMODB_TABLE_NAME}
        - name: AWS_REGION
          value: ${AWS_REGION}