apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
      - name: ${SERVICE_NAME}-container
        env:
        - name: DYNAMODB_EXPENSES_TABLE
          value: ${DYNAMODB_TABLE_NAME}
        - name: AWS_REGION
          value: ${AWS_REGION}
        - name: JAEGER_COLLECTOR
          value: otel-collector-opentelemetry-collector.observability.svc.cluster.local
          