apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
      - name: ${SERVICE_NAME}-container
        env:
        - name: DYNAMODB_PAYMENT_TABLE
          value: ${DYNAMODB_TABLE_NAME}
        - name: AWS_REGION
          value: ${AWS_REGION}