### Rule Description
##  Allow communication from User to Frontend svc pods

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-frontend
spec:
  podSelector:
    matchLabels:
      app: user
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: ${SERVICE_PORT}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: frontend
