### Rule Description
##  Allow communication from User to Frontend svc pods

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-frontend
spec:
  podSelector:
    matchLabels:
      app: user
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          ingress: frontend
    ports:
    - protocol: TCP
      port: ${SERVICE_PORT}
