apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rootdr-letsencrypt2
spec:
  acme:
    email: notreply@rootdr.info
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: rootdr-issuer-account-key
    solvers:
    - selector:
        dnsZones:
          - "rootdr.info"
      dns01:
        route53:
          region: ${AWS_REGION}