apiVersion: v1
kind: Namespace
metadata:
  name: ${ENVIRONMENT}

---

apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

