################################################
######## Force to have project-label

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredLabels
metadata:
  name: project-label
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace", "Deployment","Pod","Service"]
    namespaces: 
      - develop
      - prod
  parameters:
    labels: ["projectId"]

---

#########################################################
######## Trust in AWS ECR registry only for workloads 

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: TrustRegistry
metadata:
  name: trust-registry
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod","Job","Deployment"]
    namespaces: 
      - develop
      - prod
  parameters:
    registry: "${ECR_REGISTRY}"

---

#########################################################
######## Container Security 

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerSecurity
metadata:
  name: container-security
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod","Job"]
    namespaces: 
      - develop
      - prod