### Rule Description
##  Allow communication from ingress to frontend pods

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-frontend
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nginx-ingress
    ports:
    - protocol: TCP
      port: ${SERVICE_PORT}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nginx-ingress


--- 

### Rule Description
##  Allow communication from frontend to user

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-user
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: user
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: user
    ports:
    - protocol: TCP
      port: 80
