apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  labels:
    tier: ${TIER}
spec:
  type:  ClusterIP
  selector:
    app: ${SERVICE_NAME}
  ports:
    - port: 80
      targetPort: ${SERVICE_PORT}