apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-opa-gatekeeper
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://open-policy-agent.github.io/gatekeeper/charts