openapi: 3.1.0
info:
  version: v1
  title: FarmtStall API

servers:
 - url: 'http://smart-cash.danielrive.site/v1'

paths:
  /user/{userId}:
    get:                                        
      description: Return an user information
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:                                
        200:                                    
          description: A bunch of information about the user
          application/json:
            schema:
              $ref: '#/components/schemas/User'