apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: fluent-bit
spec:
  interval: 10m0s
  chart:
    spec:
      chart: fluent-bit
      version: 0.47.9
      sourceRef:
        kind: HelmRepository
        name: helm-fluent-bit
        namespace: flux-system
  values:
    kind: DaemonSet
    testFramework:
      enabled: false
    serviceAccount:
      create: true
    rbac:
      create: true
      nodeAccess: false
      eventsAccess: false
    hostNetwork: false
    dnsPolicy: ClusterFirst
    securityContext: 
      capabilities:
        drop:
        - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
    serviceMonitor:
      enabled: false
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /api/v1/health
        port: http
    logLevel: info
    config:
      service: |
        [SERVICE]
            Daemon Off
            Flush {{ .Values.flush }}
            Log_Level {{ .Values.logLevel }}
            Parsers_File /fluent-bit/etc/parsers.conf
            Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
            HTTP_Server On
            HTTP_Listen 0.0.0.0
            HTTP_Port {{ .Values.metricsPort }}
            Health_Check On
      inputs: |
        [INPUT]
            name            fluentbit_metrics
            tag             internal_metrics
            scrape_interval 2
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On
      outputs: |
        [OUTPUT]
            Name cloudwatch_logs
            Match kube.*
            region ${AWS_REGION} 
            log_group_name /aws/eks/${CLUSTER_NAME}/workloads
            log_stream_prefix from-k8-fluent-bit-
            auto_create_group off