apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: istio-base
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system