apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: base
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: istiod
      version: 1.25.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system