apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: base
      version: 1.26.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: istiod
      version: 1.26.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    profile: ambient

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: cni
      version: 1.26.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    profile: ambient

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: istio-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: ztunnel
      version: 1.26.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system