#########################################################
######## Trust in AWS ECR registry only for workloads 

apiVersion: constraints.gatekeeper.sh/v1beta1
kind: TrustRegistry
metadata:
  name: trust-registry
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod","Job","Deployment"]
    namespaces: 
      - develop
      - prod
  parameters:
    registry: "${ECR_REGISTRY}"

