apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
      - name: ${SERVICE_NAME}-container
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx/
        - name: nginx-cache
          mountPath: /var/cache/nginx/
  volumes:
    - name: nginx-logs
      volumeMounts:
        - name: nginx-logs
          emptyDir: {}
    - name: nginx-cache
      volumeMounts:
        - name: nginx-cache
          emptyDir: {}