apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
      - name: ${SERVICE_NAME}-container
        volumeMounts:
          - name: nginx-temp
            mountPath: /tmp/
        livenessProbe:
          httpGet:
            port: 9090  
            path: / 
          initialDelaySeconds: 1
          periodSeconds: 10
      volumes:
      - name: nginx-temp
        volumeMounts:
          - name: nginx-temp
            emptyDir: {}
