apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
      - name: ${SERVICE_NAME}-container
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx/
        - name: nginx-temp
          mountPath: /tmp/
        livenessProbe:
          httpGet:
            port: ${SERVICE_PORT}  
            path: / 
          initialDelaySeconds: 1
          periodSeconds: 10
      volumes:
      - name: nginx-logs
        volumeMounts:
          - name: nginx-logs
            emptyDir: {}
      - name: nginx-temp
        volumeMounts:
          - name: nginx-temp
            emptyDir: {}