apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-${SERVICE_NAME}
spec:
  template:
    spec:
      containers:
      - name: ${SERVICE_NAME}-container
        livenessProbe:
          httpGet:
            port: 9090  
            path: / 
          initialDelaySeconds: 1
          periodSeconds: 10