name: Develop Terraform Base-and-EKS
run-name: Dev-TF-Base-and-EKS

on: 
  workflow_dispatch:
    inputs:
      stage_to_run:
        description: 'stage name to destroy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - 1-base
          - 2-eks-cluster
          - 3-k8-common
  push:
    branches:
      - develop
      - feat/*
    paths:
      - "infra/terraform/base"
      - "infra/terraform/eks-cluster"
  pull_request:
    branches:
      - develop

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

### Define General env variables

defaults:
  run:
    shell: bash
    working-directory: ./infra/terraform
env:
  PROJECT_NAME: smart-cash
  AWS_REGION: us-west-2
  ENVIRONMENT: develop

jobs:
  VALIDATE_STAGE_UPDATED:
   runs-on: ubuntu-latest
   outputs:
      FOLDERS_UPDATED: ${{ steps.get_folders_changed.outputs.FOLDERS_UPDATED }}
   steps:
     - name: checkout-repo
       id: checkout
       uses: actions/checkout@v4
       with:
          fetch-depth: 0
     - name: Get modified services
       id: get_folders_changed
       run: |
            if [[ "${{ github.event.inputs.stage_to_run }}" == "all" ]]; then
              echo "FOLDERS_UPDATED="{"folders":["1-base-stage"]}""
            else
              . detect-folder-updated.sh  ${{ github.event.before }} ${{ github.sha }} infra
            fi
            echo "FOLDERS_UPDATED=$FOLDERS_UPDATED"
       working-directory: .github/jobs
  ### Makes a call to the workflow template defined to execute terraform, in this case the variables define the develop environment
  RUN_TERRAFORM:
    needs: VALIDATE_STAGE_UPDATED
    strategy: 
      max-parallel: 1
      matrix: ${{ fromJSON(needs.VALIDATE_STAGE_UPDATED.outputs.FOLDERS_UPDATED) }}
      fail-fast: false
    uses: danielrive/smart-cash/.github/workflows/template-run-terraform.yaml@develop
    with: 
      AWS_REGION: 'us-west-2'
      ENVIRONMENT: 'develop'
      PROJECT_NAME: 'smart-cash'
      TERRAFORM_VERSION: '1.9.2'
      AWS_IAM_ROLE_GH: 'GitHubAction-smart-cash'
      STAGE: 'base'
      FOLDER: 'base'
      ARTIFAC_ID: 'base'
    secrets:
      AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER_DEVELOP }}
      GH_TOKEN_FLUX: ${{ secrets.GH_TOKEN_FLUXCD }}
