name: Develop Terraform Base-and-EKS
run-name: Dev-TF-Base-and-EKS

on: 
  workflow_dispatch:
    inputs:
      run-all:
        description: 'Set to true if you want to ran all the steps, otherwise the workflow will detect the files that have change and run terraform those specific folders'
        required: false
        default: false
  push:
    branches:
      - develop
      - feat/*
    paths:
      - "infra/terraform/base"
      - "infra/terraform/eks-cluster"
  pull_request:
    branches:
      - develop

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

### Define General env variables

defaults:
  run:
    shell: bash
    working-directory: ./infra/terraform
env:
  PROJECT_NAME: smart-cash
  AWS_REGION: us-west-2
  ENVIRONMENT: develop

jobs:
## Execute bash script that  create s3 bucket and dynamodb table for Terraform backend
  SET_UP_TF_BACKEND:
    runs-on: ubuntu-latest
    steps:  
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER_DEVELOP }}:role/GitHubAction-smart-cash' 
          role-session-name: 'GitHub_to_AWS_via_FederatedOIDC'
          aws-region: "us-west-2"
      - name: config tf backend
        id: tf-backend
        run: ./terraform-backend.sh
        env:
          AWS_REGION: 'us-west-2'
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
        working-directory: .github/jobs/
  ### Makes a call to the workflow template defined to execute terraform, in this case the variables define the develop environment
  BASE_STAGE_DEPLOY:
    uses: danielrive/smart-cash/.github/workflows/template-run-terraform.yaml@main
    needs: SET_UP_TF_BACKEND
    with: 
      AWS_REGION: 'us-west-2'
      ENVIRONMENT: 'develop'
      PROJECT_NAME: 'smart-cash'
      TERRAFORM_VERSION: '1.4.6'
      AWS_IAM_ROLE_GH: 'GitHubAction-smart-cash'
      STAGE: 'base'
      FOLDER: 'base'
      ARTIFAC_ID: 'base'
    secrets:
      AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER_DEVELOP }}
      GH_TOKEN_FLUX: ${{ secrets.GH_TOKEN_FLUXCD }}

  EKS_STAGE_DEPLOY:
    uses: danielrive/smart-cash/.github/workflows/template-run-terraform.yaml@main
    needs: BASE_STAGE_DEPLOY
    with: 
      AWS_REGION: 'us-west-2'
      ENVIRONMENT: 'develop'
      PROJECT_NAME: 'smart-cash'
      TERRAFORM_VERSION: '1.4.6'
      AWS_IAM_ROLE_GH: 'GitHubAction-smart-cash'
      STAGE: 'eks-cluster'
      FOLDER: 'eks-cluster'
      ARTIFAC_ID: 'eks'
    secrets:
      AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER_DEVELOP }}
      GH_TOKEN_FLUX: ${{ secrets.GH_TOKEN_FLUXCD }}
