name: Develop Deploy Infra
run-name: Develop-Deploy-Infra

on: 
  workflow_dispatch:
    inputs:
      stage_to_run:
        description: 'stage name to destroy'
        required: true
        default: 'none'
        type: choice
        options:
          - 1-base-stage
          - 2-eks-cluster-stage
          - 3-k8-common-stage
  push:
    branches:
      - develop
      - feat/*
    paths:
      - "infra/**"
  pull_request:
    branches:
      - develop

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

### Define General env variables

defaults:
  run:
    shell: bash
    working-directory: ./infra/terraform
env:
  PROJECT_NAME: smart-cash
  AWS_REGION: us-west-2
  ENVIRONMENT: develop

jobs:
  VALIDATE_STAGE_UPDATED:
   runs-on: ubuntu-latest
   outputs:
      FOLDERS_UPDATED: ${{ steps.get_folders_changed.outputs.FOLDERS_UPDATED }}
   steps:
     - name: checkout-repo
       id: checkout
       uses: actions/checkout@v4
       with:
          fetch-depth: 0
     - name: Get modified services
       id: get_folders_changed
       run: |  ## IMPROVE THIS PART, BASH DOESNT FOLLOW A GOOD LOGIC
            echo "checking if an input was passed in the workflow"
            echo "input is ${{ github.event.inputs.stage_to_run }}"
            FOLDERS_UPDATED="{}"
            if [[ "${{ github.event.inputs.stage_to_run }}" != "" ]]; then    
              echo "an input was passed"
            
              FOLDERS_UPDATED_ARRAY=( ${{ github.event.inputs.stage_to_run }} ) 

              FOLDERS_MODIFIED_JSON="{\"folders\":["
            
              for item in "${FOLDERS_UPDATED_ARRAY[@]}"; do
                FOLDERS_MODIFIED_JSON+="\"$item\","
              done

              FOLDERS_MODIFIED_JSON="${FOLDERS_MODIFIED_JSON%,}"  # Remove the trailing comma
                          
              FOLDERS_MODIFIED_JSON+="]}"

              echo $FOLDERS_MODIFIED_JSON

              echo "FOLDERS_UPDATED=$FOLDERS_MODIFIED_JSON" >> $GITHUB_OUTPUT

            else
              echo "running script to detect changes automatically"
              . ./detect-folders-updated.sh  ${{ github.event.before }} ${{ github.sha }} infra
            fi
            echo $FOLDERS_UPDATED
       working-directory: .github/jobs
  ### Makes a call to the workflow template defined to execute terraform, in this case the variables define the develop environment
  RUN_TERRAFORM:
    needs: VALIDATE_STAGE_UPDATED
    strategy: 
      max-parallel: 1
      matrix: ${{ fromJSON(needs.VALIDATE_STAGE_UPDATED.outputs.FOLDERS_UPDATED) }}
      fail-fast: true
    uses: danielrive/smart-cash/.github/workflows/template-run-terraform.yaml@feat/open-api
    with: 
      AWS_REGION: 'us-west-2'
      ENVIRONMENT: 'develop'
      PROJECT_NAME: 'smart-cash'
      TERRAFORM_VERSION: '1.9.2'
      AWS_IAM_ROLE_GH: 'GitHubAction-smart-cash'
      STAGE: ${{ matrix.folders }}
    secrets:
      AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER_DEVELOP }}
      GH_TOKEN_FLUX: ${{ secrets.GH_TOKEN_FLUXCD }}
