name: build-app

#### WARNING !!!
###### For this project Pull Request will NOT be created in the GitOps repo, new tag created for the images are pushed directly to main
#####  this to avoid to many steps just for a non-prod project, if you want to re-use this code for a production env, avoid direct push to main 
#### in the GitOps repo

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string 
      SERVICE_NAME:
        required: true 
        type: string
    secrets:
      AWS_ACCOUNT_NUMBER:
        required: true
      GH_TOKEN_FLUX:
        required: true
env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com
  ECR_REPOSITORY: ${{ inputs.SERVICE_NAME }}-${{ inputs.PROJECT_NAME }}
  AWS_IAM_ROLE_GH: 'GitHubAction-smart-cash'
  GH_USERNAME: danielrive 

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.build-and-push.outputs.IMAGE_TAG }}
    steps:
      - name: checkout-repo
        id: checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        id: set-up-qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: set-up-buildx
        uses: docker/setup-buildx-action@v2
      - name: configure aws credentials
        id: aws-creds-config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/${{ env.AWS_IAM_ROLE_GH }}'
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Login AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build containter
        id: build-and-push
        working-directory: './${{ inputs.SERVICE_NAME }}'
        run: | 
            COMMIT_ID=${{ github.sha}}

            SHORT_COMMIT_ID="${COMMIT_ID:0:6}"
            
            echo "${{ github.ref }}"
            
            docker buildx build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ inputs.ENVIRONMENT }} --push --platform linux/amd64 .

            #docker buildx build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ inputs.ENVIRONMENT }}-$SHORT_COMMIT_ID --push --platform linux/amd64 .

            #echo "Tag the image with the env name"
            
            

  

 