name: Microservice deploy DEVELOP
run-name: Dev-Microservice-deploy

on: 
  workflow_dispatch:
    inputs:
      run-all:
        description: 'Set to true if you want to ran all the steps, otherwise the workflow will detect the files that have change and run terraform those specific folders'
        required: false
        default: false
  push:
    branches:
      - develop
      - feat/*
    paths-ignore:
      - '.github/**'
      - 'infra/**'
  
permissions:
  id-token: write 
  contents: read

defaults:
  run:
    shell: bash
    
jobs:
  validate-service-updated:
   runs-on: ubuntu-latest
   outputs:
      FOLDERS_UPDATED: ${{ steps.get_folders_changed.outputs.FOLDERS_UPDATED }}
   steps:
     - name: checkout-repo
       id: checkout
       uses: actions/checkout@v4
       with:
          fetch-depth: 0
     - name: Get modified services
       id: get_folders_changed
       run: |
          . detect-folders-updated.sh  ${{ github.event.before }} ${{ github.sha }} ${{ github.event.inputs.run-all }}
          echo "getting file"
       working-directory: .github/jobs

  service-build:
    needs: validate-service-updated
    strategy: 
      matrix: ${{ fromJSON(needs.validate-service-updated.outputs.FOLDERS_UPDATED) }}
      fail-fast: false
    uses: danielrive/smart-cash/.github/workflows/template-service-deploy.yaml@main
    with: 
      AWS_REGION: us-west-2
      ENVIRONMENT: 'develop'
      PROJECT_NAME: 'smart-cash'
      SERVICE_NAME: ${{ matrix.folders }}
    secrets:
      AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER_DEVELOP }}
      GH_TOKEN_FLUX: ${{ secrets.GH_TOKEN_FLUXCD }}